import {defineMessages} from 'react-intl';

const messages = {
  aboutTitle: 'Over Onze Business',
  aboutSubtitle: 'Automatiseer en je bent vertrokken!',
  aboutP1: 'Heb je er ooit bij stilgestaan hoeveel tijd je dagelijks verspilt aan parameters nakijken en gegevens vertalen naar complexe rapporten? Word jij er gelukkiger van om eindeloze data te trekken uit verschillende documenten en deze dan nog in een gestructureerd overzicht proberen te gieten? Of nog erger, hoe voel jij je als je dezelfde webpagina keer op keep moet updaten en nakijken?',
  aboutP2: 'Ook al mogen deze zaken dan wel essentieel zijn voor je business, we weten allemaal dat het niet de zaken zijn die zorgen voor de meeste voldoening.',
  aboutP3: 'Ik herinner me mijn eerste job als Taks Consultant. Eén van mijn eerste projecten hield in dat ik verschillende benchmark analyses moest uitvoeren. Om mijn werk goed te doen moest ik het internet afschuimen om de nodige informatie te dataminen. Helaas voor mij is dataminen enkel een mooie manier om te zeggen dat ik op 200 sites moest klikken om een bepaalde parameter te kunnen bepalen. Ik hoef je niet te vertellen dat ik van deze opdracht niet bepaald gelukkig werd. Ik besefte wel dat dit cruciaal was voor het project maar ik voelde me er niet heel voldaan bij.',
  aboutP4: 'En dat is nu precies waar wij, bij SyPiCo, voor jou het verschil kunnen maken! We helpen jou met plezier de nodige data te verzamelen, organiseren en analyseren. Het mag duidelijk zijn: onze missie is ervoor zorgen dat jij gelukkig en voldaan in bed kan kruipen na een productieve werkdag. Al wat jou nog rest om goed te slapen is ons contacteren en dan zorgen wij dat onze geautomatiseerde processen jouw zorgen overnemen.',
  aboutP5: 'SyPiCo wil garanderen dat ambitieuze werknemers zoals jij gemotiveerd blijven. Wij zorgen ervoor dat jij de meest saaie en repetitieve taken uit handen kan geven. Onze kennis en software zorgen ervoor dat we zelfs de meest complexe kwesties uit jouw organisatie kunnen aanpakken.',
  aboutP6: 'Helemaal klaar om weer vol goede moed verder te werken en ons de zorgen te laten overnemen? Bel ons vandaag nog op en we bespreken met plezier waar wij een meerwaarde kunnen betekenen voor jou.',
  languageSelector: 'Language',
  languageSelectorEN: 'English',
  languageSelectorNL: 'Dutch',
  navBarHome: 'Home',
  navBarServices: 'Diensten',
  navBarOurWork: 'Ons werk',
  navBarTeam: 'Team',
  navBarTestimonials: 'Testimonials',
  navBarAbout: 'Bedrijf',
  navBarContact: 'Contacteer ons',
  navBarCareers: 'Jobs',
  bannerSubtitle: 'Automatiseer - en je bent vertrokken!',
  bannerGetStarted: 'Get Started',
  bannerHowItWorks: 'How it works',
  servicesTitle: 'SyPiCo Services',
  servicesSubtitle: 'Helemaal klaar om weer vol goede moed verder te werken en ons de zorgen te laten overnemen? Bel ons vandaag nog op en we bespreken met plezier waar wij een meerwaarde kunnen betekenen voor jou.',
  servicesServiceDataGatheringTitle: 'Gegevensverzameling',
  servicesServiceDataGatheringDescription: 'De combinatie van onze skills en inzichten zorgen ervoor dat we jouw gegevensverzameling makkelijk kunnen transformeren in eenvoudige processen. We kunnen jou helpen om deze tijdrovende taken te automatiseren en zo de werkdruk voor je werknemers aanzienlijk te verlagen. Hetzelfde werk dat hen anders zeer gedemotiveerd zou maken kunnen wij in een vingerknip overnemen en up to date houden.',
  servicesDataAnalyticsTitle: 'Data analyses',
  servicesDataAnalyticsDescription: 'He je nood aan nieuwe inzichten in jouw bulkgegevens? Laat ons helpen. Elke onderneming streeft naar vooruitgang maar in de veranderende omgeving van vandaag is dit pas echt mogelijk als je slimme en gefundeerde beslissingen kan nemen. Door onze data analyses helpen wij jou in elk geval al sterk op weg naar de toekomst.',
  ourWorkTitle: 'Onze projecten',
  ourWorkSubtitle: 'Wij helpen je saaie en repetitieve opdrachten te automatiseren!',
  ourWorkGetInTouch: 'Contacteer ons',
  ourWorkDataAnalyticsTitle: 'Data analyse',
  ourWorkDataAnalyticsDescription: 'It became clear that price setting in the house renting business is crucial but also rather complex as it is very dependent on season and events. We took it upon us to crunch the numbers and analyze their data in detail. Our Data Analytics resulted in a revenue increase of 10%.',
  ourWorkAutomationToolTitle: 'Automation tool',
  ourWorkAutomationToolDescription: 'Master-planning list is automatically updated every five minutes. Thanks to SyPiCo no more precious time is wasted and resources are used much more efficiently.',
  teamTitle: 'Our Expert Team',
  teamBusinessDeveloperTitle: 'Business Developer',
  teamBusinessDeveloperDescription: 'Gabriel is jouw referentie als het gaat over klantenrelaties en business ontwikkeling.',
  teamDataAnalystTitle: 'Data Analyst',
  teamDataAnalystDescription: 'Robin is ons analytisch talent die details ziet als geen ander. Hij kan je perfect verder helpen bij het automatiseren van lastige en monotone taken.',
  testimonialsReadMore: 'Read more',
  contactUsTitle: 'Contacteer ons',
  contactUsName: 'Naam',
  contactUsEmail: 'Emailadres',
  contactUsMessage: 'Bericht',
  contactUsSubmit: 'Verstur',
  careersTitle: 'We\'re looking for new talent!',
  careersInternship: 'Internship',
  careersSoftwareDeveloper: 'Software Developer',
  footerContactUs: 'Contact Us',
  footerPrivacyPolicy: 'Privacy Policy',
  footerTermsAndConditions: 'Terms &amp; Conditions',
};

export default defineMessages(messages);